version: '3.8'
services:
  node-docker:
    container_name: node-docker
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5000/udp
      - 6001:6000/tcp
      - 8001:8000/tcp
      - 9001:9000/tcp
    networks:
      - kekNetwork
networks:
  kekNetwork: